"""init

Revision ID: 0d6646b85c2f
Revises:
Create Date: 2025-04-18 15:01:43.187518

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

import app.core.typess

# revision identifiers, used by Alembic.
revision: str = "0d6646b85c2f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chats",
        sa.Column(
            "uid", sa.Integer(), autoincrement=True, nullable=False, comment="Chat ID"
        ),
        sa.Column(
            "first_name",
            sa.String(length=64),
            nullable=True,
            comment="Customer first name",
        ),
        sa.Column(
            "last_name",
            sa.String(length=64),
            nullable=True,
            comment="Customer last name",
        ),
        sa.Column(
            "patronymic_name",
            sa.String(length=64),
            nullable=True,
            comment="Chat patronymic name",
        ),
        sa.Column(
            "phone_number",
            sa.String(length=64),
            nullable=True,
            comment="Chat phone number",
        ),
        sa.Column("email", sa.String(length=128), nullable=True, comment="Chat email"),
        sa.Column("rating", sa.SmallInteger(), nullable=False, comment="Chat rating"),
        sa.PrimaryKeyConstraint("uid"),
    )
    op.create_table(
        "users",
        sa.Column("uid", sa.UUID(), nullable=False, comment="User ID"),
        sa.Column(
            "first_name", sa.String(length=64), nullable=True, comment="User first name"
        ),
        sa.Column(
            "last_name", sa.String(length=64), nullable=True, comment="User last name"
        ),
        sa.Column(
            "patronymic_name",
            sa.String(length=64),
            nullable=True,
            comment="User patronymic name",
        ),
        sa.Column("email", sa.String(length=128), nullable=False, comment="User email"),
        sa.Column(
            "phone_number",
            sa.String(length=64),
            nullable=True,
            comment="User phone number",
        ),
        sa.Column(
            "password", sa.String(length=64), nullable=False, comment="User password"
        ),
        sa.PrimaryKeyConstraint("uid"),
    )
    op.create_table(
        "messages",
        sa.Column(
            "uid",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Message ID",
        ),
        sa.Column("chat_uid", sa.Integer(), nullable=False, comment="Chat ID"),
        sa.Column(
            "text", sa.String(length=1024), nullable=True, comment="Message text"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Message created at",
        ),
        sa.Column("user_uid", sa.UUID(), nullable=True, comment="User ID"),
        sa.ForeignKeyConstraint(
            ["chat_uid"],
            ["chats.uid"],
        ),
        sa.ForeignKeyConstraint(
            ["user_uid"],
            ["users.uid"],
        ),
        sa.PrimaryKeyConstraint("uid"),
    )
    op.create_table(
        "permissions",
        sa.Column(
            "code",
            sa.Enum(
                "C_USER",
                "R_USER",
                "U_USER",
                "D_USER",
                "C_MESSAGE",
                "R_MESSAGE",
                "U_MESSAGE",
                "D_MESSAGE",
                "R_CHAT",
                "U_CHAT",
                "D_CHAT",
                "C_PERMISSION",
                "R_PERMISSION",
                "U_PERMISSION",
                "D_PERMISSION",
                name="permissioncode",
            ),
            nullable=False,
            comment="Permission code",
        ),
        sa.Column("user_uid", sa.UUID(), nullable=False, comment="User ID"),
        sa.ForeignKeyConstraint(
            ["user_uid"],
            ["users.uid"],
        ),
        sa.PrimaryKeyConstraint("code", "user_uid"),
    )
    op.create_table(
        "message_files",
        sa.Column(
            "uid",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Message file ID",
        ),
        sa.Column("name", sa.String(length=256), nullable=False, comment="File name"),
        sa.Column(
            "path", app.core.typess.PathType(), nullable=False, comment="File path"
        ),
        sa.Column("message_uid", sa.Integer(), nullable=False, comment="Message ID"),
        sa.ForeignKeyConstraint(["message_uid"], ["messages.uid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("message_files")
    op.drop_table("permissions")
    op.drop_table("messages")
    op.drop_table("users")
    op.drop_table("chats")
    # ### end Alembic commands ###
    # ### end Alembic commands ###
